name: Check black coding style

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black Check
        uses: psf/black@stable
        with:
          version: "21.12b0"